export enum Tema {
  MATEMATICAS = 'MATEMATICAS',
  FISICA = 'FISICA',
  QUIMICA = 'QUIMICA',
  BIOLOGIA = 'BIOLOGIA',
  INGLES = 'INGLES',
  LITERATURA = 'LITERATURA',
  HISTORIA = 'HISTORIA',
  PROGRAMACION = 'PROGRAMACION',
  BASE_DATOS = 'BASE_DATOS',
  INFRAESTRUCTURA = 'INFRAESTRUCTURA',
  OTROS = 'OTROS'
}
