export enum Tema {
  MATEMATICAS = 'MATEMATICAS',
  LENGUAJE = 'LENGUAJE',
  CIENCIAS_NATURALES = 'CIENCIAS_NATURALES',
  CIENCIAS_SOCIALES = 'CIENCIAS_SOCIALES',
  INGLES = 'INGLES',
  TECNOLOGIA = 'TECNOLOGIA',
  INFORMATICA = 'INFORMATICA',
  OTRO = 'OTRO'
}

export enum EstadoSolicitud {
  ABIERTA = 'ABIERTA',
  EN_PROCESO = 'EN_PROCESO',
  CERRADA = 'CERRADA'
}