export enum TipoContenido {
  VIDEO = 'VIDEO',
  ARTICULO = 'ARTICULO',
  LIBRO = 'LIBRO',
  EJERCICIO = 'EJERCICIO',
  INFOGRAFIA = 'INFOGRAFIA',
  PODCAST = 'PODCAST',
  PRESENTACION = 'PRESENTACION',
  OTRO = 'OTRO'
}
